version: '3.8'

# Custom top-level network
networks:
  neo4j-internal:

services:

  server1:
    # Image Docker
    image: ${NEO4J_DOCKER_IMAGE}

    # Hostname
    hostname: server1

    # Réseau du cluster (à utiliser dans neo4j.conf pour la découverte du cluster) 
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network

    # HTTP (7474) et Bolt (7687).
    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      #- ./data/server1:/var/lib/neo4j/data
      #- ./logs/server1:/var/lib/neo4j/logs
      - ./conf/server1:/var/lib/neo4j/conf
      #- ./import/server1:/var/lib/neo4j/import
      #- ./metrics/server1:/var/lib/neo4j/metrics
      #- ./licenses/server1:/var/lib/neo4j/licenses
      #- ./ssl/server1:/var/lib/neo4j/ssl

    # Les variables d'environnement à utiliser et qui doivent être préalablement intialisées (voir plus bas)
    # Seuelemt la variable pour le choix du mode est intialisé ici
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      #- NEO4J_initial_server_mode__constraint=PRIMARY

    # Vérifier que le port 7474 est ouvert
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]

    # Utilisateur/Groupe
    #user: ${USER_ID}:${GROUP_ID}

  server2:
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: server2
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      #- ./neo4j.conf:/conf/neo4j.conf
      #- ./data/server2:/var/lib/neo4j/data
      #- ./logs/server2:/var/lib/neo4j/logs
      - ./conf/server2:/var/lib/neo4j/conf
      #- ./import/server2:/var/lib/neo4j/import
      #- ./metrics/server2:/var/lib/neo4j/metrics
      #- ./licenses/server2:/var/lib/neo4j/licenses
      #- ./ssl/server2:/var/lib/neo4j/ssl
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      #- NEO4J_initial_server_mode__constraint=PRIMARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    #user: ${USER_ID}:${GROUP_ID}

  server3:
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: server3
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7476:7474"
      - "7689:7687"
    volumes:
      #- ./neo4j.conf:/conf/neo4j.conf
      #- ./data/server3:/var/lib/neo4j/data
      #- ./logs/server3:/var/lib/neo4j/logs
      - ./conf/server3:/var/lib/neo4j/conf
      #- ./import/server3:/var/lib/neo4j/import
      #- ./metrics/server3:/var/lib/neo4j/metrics
      #- ./licenses/server3:/var/lib/neo4j/licenses
      #- ./ssl/server3:/var/lib/neo4j/ssl
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      #- NEO4J_initial_server_mode__constraint=PRIMARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    #user: ${USER_ID}:${GROUP_ID}

  server4:
    image: ${NEO4J_DOCKER_IMAGE}
    hostname: server4
    networks:
      neo4j-internal:
        aliases:
          - neo4j-network
    ports:
      - "7477:7474"
      - "7690:7687"
    volumes:
      #- ./neo4j.conf:/conf/neo4j.conf
      #- ./data/server4:/var/lib/neo4j/data
      #- ./logs/server4:/var/lib/neo4j/logs
      - ./conf/server4:/var/lib/neo4j/conf
      #- ./import/server4:/var/lib/neo4j/import
      #- ./metrics/server4:/var/lib/neo4j/metrics
      #- ./licenses/server4:/var/lib/neo4j/licenses
      #- ./ssl/server4:/var/lib/neo4j/ssl
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_AUTH
      - EXTENDED_CONF
      - NEO4J_EDITION
      #- NEO4J_initial_server_mode__constraint=SECONDARY
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
    #user: ${USER_ID}:${GROUP_ID}
