services:
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
        - '9094:9094' #1
        environment:
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_CONTROLLER_BROKER_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094 #2
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094 #3
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT #4
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    kafka-ui:
        image: 'provectuslabs/kafka-ui:latest'
        ports:
        - '8081:8080'
        depends_on:
        - kafka
        environment:
        - KAFKA_CLUSTERS_0_NAME=local #5
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 #6
    spark:
        image: jupyter/all-spark-notebook:x86_64-ubuntu-22.04
        command: start.sh jupyter lab --NotebookApp.token=''
        ports:
        - "8080:8080"
        - "7077:7077"
        - "8888:8888"
        environment:
        - JUPYTER_ENABLE_LAB="no"
        volumes:
        - ./spark_notebooks:/home/jovyan/ateliers


        depends_on:
        - kafka